version: '3'
services:
  omnio_postgres:
    container_name: omnio_postgres
    image: postgres:14-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - omnio_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi

  omnio_adminer:
    container_name: omnio_adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: omnio_postgres
    networks:
      - strapi
    depends_on:
      - omnio_postgres

volumes:
  omnio_data:

networks:
  strapi:
    driver: bridge